### ISSUE TITLE
Magento Installation Step

### ISSUE THREAD

**Issue by FATCDN** [centminmod/centminmod-magento2#3]
# magento installation
`time php $WEBROOT/bin/magento setup:install --base-url=https:/${vhostname}/ \`

should be

`time php $WEBROOT/bin/magento setup:install --base-url=https://${vhostname}/ \`

**Comment by centminmod** [comment]
cheers @FATCDN fixed https://github.com/centminmod/centminmod-magento2/commit/b69e304a4324c6494dd77d10560ee20661aba1f7 :)
